In [5]:
print("Hello World!")

Hello World!

In [6]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [11]:
import pandas as pd

In [12]:
data =[1,2,3,4,5]
series= pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
marks = pd.Series([90,90,90], index =['Maths', 'English', 'Nepali'])
marks

Maths      90
English    90
Nepali     90
dtype: int64

In [14]:
print(marks['Maths'])

90

In [15]:
import pandas as pd

# FIX: Use colons (:) to connect the letter to the number
data_dictionary = {
    'a': 1, 
    'b': 2,
    'c': 3
}

series_direct = pd.Series(data_dictionary)
print(series_direct)

a    1
b    2
c    3
dtype: int64

In [16]:
#Series Real Example
Stock_prices = pd.Series([157,156,143,123,453], index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])
print(Stock_prices['Tuesday'])

156

In [17]:
# Calculate the Mean 
mean_price = Stock_prices.mean()
print("Mean Stock Price:", mean_price)

#Calculate the Median
median_price = Stock_prices.median()
print("Median Stock Price:", median_price)

#Calculate the Max Value
max_price = Stock_prices.max()
print("Max Stock Price:", max_price)

Mean Stock Price: 206.4
Median Stock Price: 156.0
Max Stock Price: 453

In [18]:
print(Stock_prices.describe())
print(Stock_prices.value_counts())
print(Stock_prices[Stock_prices > 150])

count      5.000000
mean     206.400000
std      138.534472
min      123.000000
25%      143.000000
50%      156.000000
75%      157.000000
max      453.000000
dtype: float64
157    1
156    1
143    1
123    1
453    1
Name: count, dtype: int64
Monday     157
Tuesday    156
Friday     453
dtype: int64

In [19]:
df.describe()

NameError: name 'df' is not defined

In [20]:
# Dateframe with tow dimensional saa with the rows and columns
df = pd.DataFrame(data)


data={
    'Name': ['Kritam', 'Manish', 'Khagen'],
    'Age': [22, 23, 24],
    'Address': ['Kathmandu', 'Lalitpur', 'Bhaktapur']
}

In [21]:
df = pd.DataFrame(data)
print(df)

     Name  Age    Address
0  Kritam   22  Kathmandu
1  Manish   23   Lalitpur
2  Khagen   24  Bhaktapur

In [22]:
df.head(3)

     Name  Age    Address
0  Kritam   22  Kathmandu
1  Manish   23   Lalitpur
2  Khagen   24  Bhaktapur

In [23]:
df.tail(1)

     Name  Age    Address
2  Khagen   24  Bhaktapur

In [24]:
# column Name
df['Name']

0    Kritam
1    Manish
2    Khagen
Name: Name, dtype: str

In [66]:
df.shape

(3, 3)

In [67]:
df['Name']

0    Kritam
1    Manish
2    Khagen
Name: Name, dtype: str

In [25]:
#Filtering Dataframe
filtered_df = df[df['Age'] > 22]
print(filtered_df)

     Name  Age    Address
1  Manish   23   Lalitpur
2  Khagen   24  Bhaktapur

In [26]:
#Multiple Condition
filtered_df = df[(df['Age'] > 22) & (df['Address'] == 'Lalitpur')]
print(filtered_df)

     Name  Age   Address
1  Manish   23  Lalitpur

In [27]:
#Or condition
filtered_df = df[(df['Age'] > 22) | (df['Address'] == 'Lalitpur')]
print(filtered_df)

     Name  Age    Address
1  Manish   23   Lalitpur
2  Khagen   24  Bhaktapur

In [28]:
#Add Upadate Delete 
#Adding new Column
df['Salary'] = [50000, 60000, 55000]
print(df)

     Name  Age    Address  Salary
0  Kritam   22  Kathmandu   50000
1  Manish   23   Lalitpur   60000
2  Khagen   24  Bhaktapur   55000

In [29]:
# Updating the existing column with Conditions
df.loc[df['Name'] == 'Kritam', 'Salary'] = 52000
print(df)

     Name  Age    Address  Salary
0  Kritam   22  Kathmandu   52000
1  Manish   23   Lalitpur   60000
2  Khagen   24  Bhaktapur   55000

In [14]:
import pandas as pd 

#Reading the CSV file
df_csv = pd.read_csv('sample_users.csv')

print(df_csv.tail(5))

    first_name  last_name                   company_name           address  \
495    Brittni  Gillaspie                    Inner Label        67 Rv Cent
496    Raylene      Kampa                     Hermar Inc    2 Sw Nyberg Rd
497        Flo   Bookamer   Simonton Howe & Schneider Pc   89992 E 15th St
498       Jani      Biddy  Warehouse Office & Paper Prod  61556 W 20th Ave
499   Chauncey     Motley     Affiliated With Travelodge    63 E Aurora Dr

         city     county state    zip        phone1        phone2  \
495     Boise        Ada    ID  83709  208-709-1235  208-206-9848
496   Elkhart    Elkhart    IN  46514  574-499-1454  574-330-1884
497  Alliance  Box Butte    NE  69301  308-726-2182  308-250-6987
498   Seattle       King    WA  98104  206-711-6498  206-395-6284
499   Orlando     Orange    FL  32804  407-413-4842  407-557-8857

                        email                                      web
495  bgillaspie@gillaspie.com                http://www.innerlabel.com
496          rkampa@kampa.org                 http://www.hermarinc.com
497      flo.bookamer@cox.net   http://www.simontonhoweschneiderpc.com
498          jbiddy@yahoo.com  http://www.warehouseofficepaperprod.com
499   chauncey_motley@aol.com  http://www.affiliatedwithtravelodge.com