In [5]:
print("Hello World!")

Hello World!

In [6]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\KRITAM\anaconda3\envs\nlp311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [9]:
import pandas as pd

In [11]:
data =[1,2,3,4,5]
series= pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
marks = pd.Series([90,90,90], index =['Maths', 'English', 'Nepali'])
marks

Maths      90
English    90
Nepali     90
dtype: int64

In [23]:
print(marks['Maths'])

90

In [27]:
import pandas as pd

# FIX: Use colons (:) to connect the letter to the number
data_dictionary = {
    'a': 1, 
    'b': 2,
    'c': 3
}

series_direct = pd.Series(data_dictionary)
print(series_direct)

a    1
b    2
c    3
dtype: int64

In [29]:
#Series Real Example
Stock_prices = pd.Series([157,156,143,123,453], index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])
print(Stock_prices['Tuesday'])

156

In [30]:
# Calculate the Mean 
mean_price = Stock_prices.mean()
print("Mean Stock Price:", mean_price)

#Calculate the Median
median_price = Stock_prices.median()
print("Median Stock Price:", median_price)

#Calculate the Max Value
max_price = Stock_prices.max()
print("Max Stock Price:", max_price)

Mean Stock Price: 206.4
Median Stock Price: 156.0
Max Stock Price: 453

In [32]:
print(Stock_prices.describe())
print(Stock_prices.value_counts())
print(Stock_prices[Stock_prices > 150])

count      5.000000
mean     206.400000
std      138.534472
min      123.000000
25%      143.000000
50%      156.000000
75%      157.000000
max      453.000000
dtype: float64
157    1
156    1
143    1
123    1
453    1
Name: count, dtype: int64
Monday     157
Tuesday    156
Friday     453
dtype: int64

In [48]:
df.describe()

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [61]:
# Dateframe with tow dimensional saa with the rows and columns



data={
    'Name': ['Kritam', 'Manish', 'Khagen'],
    'Age': [22, 23, 24],
    'Address': ['Kathmandu', 'Lalitpur', 'Bhaktapur']
}

In [62]:
df = pd.DataFrame(data)
print(df)

     Name  Age    Address
0  Kritam   22  Kathmandu
1  Manish   23   Lalitpur
2  Khagen   24  Bhaktapur

In [63]:
df.head(3)

     Name  Age    Address
0  Kritam   22  Kathmandu
1  Manish   23   Lalitpur
2  Khagen   24  Bhaktapur

In [64]:
df.tail(1)

     Name  Age    Address
2  Khagen   24  Bhaktapur

In [65]:
# column Name
df['Name']

0    Kritam
1    Manish
2    Khagen
Name: Name, dtype: str

In [66]:
df.shape

(3, 3)

In [67]:
df['Name']

0    Kritam
1    Manish
2    Khagen
Name: Name, dtype: str

In [68]:
#Filtering Dataframe
filtered_df = df[df['Age'] > 22]
print(filtered_df)

     Name  Age    Address
1  Manish   23   Lalitpur
2  Khagen   24  Bhaktapur